name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build and Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/.cache/turbo/
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: npm run deploy --cache-dir="./node_modules/.cache/turbo/"
